### ISSUE TITLE
Add options for config file

### ISSUE THREAD

**Issue by sidhujasminder** [jtishey/jsnapy_flask#1]
First of all the Application is working great. To add a few new enhancements, as discussed with @vnitinv, need to add options for the config file through the webpage. 

As a suggestion you can add input for user, hostname, and password. Then ask the user which testfile does he want to run, through a dropdown or something like that. After this we can try to add all the parameters of the config through the webpage, then the entire config file will be created at the runtime. 

What you say?

**Comment by jtishey** [comment]
Sounds good.  I had started working on a Settings page or pop-up previoisly but scrapped it at the time to get the basics working first.

**Comment by jtishey** [comment]
It's not pretty or secure, and I'm not entirely sure on how to make it cooperate with virtualenv, but take a look at the latest commit and let me know what you think.
